export { default as useDetail } from './useDetail'
export { default as useTable } from './useTable'
export { default as useTitlePage } from './useTitlePage'
export { default as useSimpleTable } from './useSimpleTable'
export { useTitle } from './useTitle'
