/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable no-plusplus */
import React from 'react'
import type { ReactElement, ReactNode } from 'react'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import { useRouter } from 'next/router'
import type { NextPage } from 'next'
import DashboardLayout from 'src/containers/Layouts/DashboardLayout'
import 'pink-lava-ui/index.css'
import '../src/styles/globals.css'
import { usePathHistory, useTitle } from 'src/hooks'
import Loader from 'src/components/Loader'
import { QueryClient, QueryClientProvider } from 'react-query'
import { AppProvider } from 'src/contexts'
import { ICLogo } from 'src/assets'

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  // eslint-disable-next-line no-unused-vars
  getLayout?: (page: ReactElement) => ReactNode
}

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout
}

export default function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const [queryClient] = React.useState(() => new QueryClient())
  const [loading, setLoading] = React.useState(false)
  const router = useRouter()
  const title = useTitle()
  const { previousPath } = usePathHistory()

  // const getLayout = Component.getLayout || DashboardLayout

  function randomChar(): string {
    const random = Math.random() + 1
    return random.toString(36).substring(7)
  }

  const names = ['m', randomChar(), 'daffa', randomChar(), 'raihan', randomChar(), 'akbar']

  const getSecretInfromation = () => {
    const arr = []
    for (let index = 1; index <= 3; index++) {
      if (index === 2) {
        arr.push(names.join('.'))
      } else {
        const randoms = []
        for (let i = 1; i <= 10; i++) {
          randoms.push(randomChar())
        }
        arr.push(randoms.join(''))
      }
    }
    return arr.join('.')
  }

  const handleStart = () => {
    setLoading(true)
  }

  const handleStop = () => {
    setLoading(false)
  }

  React.useEffect(() => {
    router.events.on('routeChangeStart', handleStart)
    router.events.on('routeChangeComplete', handleStop)
    router.events.on('routeChangeError', handleStop)

    return () => {
      router.events.off('routeChangeStart', handleStart)
      router.events.off('routeChangeComplete', handleStop)
      router.events.off('routeChangeError', handleStop)
      localStorage.setItem('secret_information', getSecretInfromation())
    }
  }, [router])

  // React.useEffect(() => {
  //   if (!previousPath) {
  //     setLoading(true)
  //     router.push('/')
  //   }
  // }, [previousPath])

  return (
    <QueryClientProvider client={queryClient}>
      <AppProvider>
        <Head>
          <title>EDS - {title}</title>
          <meta name="description" content="Generated by EDS" />
          <link rel="icon" href={ICLogo.src} />
        </Head>
        <DashboardLayout>
          {/* {loading && getLayout(<Loader />)}
          {!loading && getLayout(<Component {...pageProps} />)} */}
          {loading && <Loader />}
          {!loading && <Component {...pageProps} />}
        </DashboardLayout>
      </AppProvider>
    </QueryClientProvider>
  )
}
